export const routeMap = {
  '/admin-dashboard': 'admin-dashboard',
  '/customer-care-dashboard': 'customer-care-dashboard',
  '/customer-cart': 'customer-cart',
  '/customer-dashboard': 'customer-dashboard',
  '/customer-login': 'customer-login',
  '/customer-loyalty': 'customer-loyalty',
  '/customer-orders': 'customer-orders',
  '/customer-product': 'customer-product',
  '/customer-register': 'customer-register',
  '/customer-reset-password': 'customer-reset-password',
  '/customer-shop': 'customer-shop',
  '/customer-support': 'customer-support',
  '/': 'home',
  '/inventory-dashboard': 'inventory-dashboard',
  '/loyalty-management-dashboard': 'loyalty-management-dashboard',
  '/order-management-dashboard': 'order-management-dashboard',
  '/product-management-dashboard': 'product-management-dashboard',
  '/staff-login': 'staff-login',
  '/staff-register': 'staff-register',
};
